# Generated by Django 5.2.1 on 2025-05-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitap',
            options={'verbose_name': 'Kitap', 'verbose_name_plural': 'Kitaplar'},
        ),
        migrations.AlterField(
            model_name='kitap',
            name='aciklama',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Kitap Adı'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='yayin_tarihi',
            field=models.DateField(verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='yazar',
            field=models.CharField(max_length=100, verbose_name='Yazar Adı'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitaplar.kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
