# Generated by Django 5.2.1 on 2025-05-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0002_alter_kitap_options_alter_kitap_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitap',
            options={},
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='aciklama',
        ),
        migrations.AlterField(
            model_name='kitap',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='isim',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='yayin_tarihi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='yazar',
            field=models.CharField(max_length=255),
        ),
    ]
