# Generated by Django 5.2.1 on 2025-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0004_remove_kitap_yayin_tarihi_kitap_resim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitap',
            name='isim',
        ),
        migrations.AddField(
            model_name='kitap',
            name='aciklama',
            field=models.TextField(default='Varsayılan Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitap',
            name='baslik',
            field=models.CharField(default='Varsayılan Başlık', max_length=200),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='resim',
            field=models.ImageField(default='Varsayılan Başlık', upload_to='kitap_resimleri/'),
            preserve_default=False,
        ),
    ]
