# Generated by Django 5.2.1 on 2025-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0005_remove_kitap_isim_kitap_aciklama_kitap_baslik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
    ]
