# Generated by Django 5.2.1 on 2025-05-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0006_alter_kitap_baslik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitap',
            name='aciklama',
        ),
    ]
